# Generated by Django 3.0.8 on 2020-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField('Author', 'last_name', models.CharField(default='',max_length=100))
    ]
